export AUTH0_DOMAIN='your-domain.auth0.com'
export AUTH0_CLIENTID='YouRAuth0ClientId'
export COGNITO_REGION='us-west-2'
export COGNITO_USERPOOLID='us-west-2_yourUserPoolId'
export COGNITO_CLIENTID='AwSCognitoClientId'
export OKTA_ISSUER='http://{your-okta-org-url}/oauth2/default'